name: Dump firmware(s)

on:
  workflow_dispatch:
    inputs:
      urls:
        description: 'URLs (space or comma-separated)'
        required: true
      codename:
        description: 'Device'
        required: true
        type: choice
        options:
          - dodge
          - pagani
          - erhai
          - giulia
          - waffle
          - aston
      region:
        description: 'Region'
        required: true
        type: choice
        options:
          - IN
          - NA
          - CN
          - ROW

jobs:
  dump:
    permissions: write-all
    runs-on: self-hosted

    steps:      
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Dump
      id: dump
      run: |
        IFS=',' read -ra URLS <<< "${{ inputs.urls }}"
        URL_ARGS=""
        for url in "${URLS[@]}"; do
          URL_ARGS+="$url "
        done
        ./dump.sh ${{ inputs.codename }} ${{ inputs.region }} $URL_ARGS "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

    - name: Upload release assets
      uses: ncipollo/release-action@v1.20.0
      with:
        artifacts: out/*
        artifactErrorsFailBuild: true
        body: ${{ steps.dump.outputs.body }}
        tag: ${{ steps.dump.outputs.tag }}_${{ github.event.inputs.region }}
        token: ${{ secrets.GITHUB_TOKEN }}
