name: Dump firmware(s)

on:
  workflow_dispatch:
    inputs:
      urls:
        description: 'URLs'
        required: true
      region:
        description: 'Region'
        required: true
        type: choice
        options:
          - IN
          - EU
          - GLO
          - NA
          - CN

jobs:
  dump:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup
      run: |
        sudo apt update
        sudo apt -y install aria2 zstd p7zip-full parallel openssl xxhash

    - name: Dump
      id: dump
      run: echo ${{ inputs.urls }} | xargs ./dump.sh

    - name: Upload release assets
      uses: ncipollo/release-action@v1
      with:
        artifacts: out/*
        artifactErrorsFailBuild: true
        body: ${{ steps.dump.outputs.body }}
        tag: ${{ steps.dump.outputs.tag }}_${{ github.event.inputs.name }}
        token: ${{ secrets.GITHUB_TOKEN }}
